/** Generated from Flutter menu_screen_url.dart — paths only; hosts in env / Vite proxy. */
export const menuScreenUrls = {
  i18nManagement: 'i18n-management',
  bannerConfiguration: 'banner-configuration',
  menuEntitlement: 'menu-entitlement',
  termCondition: 'term-condition',
  pushNotification: 'notification/push-notification',
  messagesCampaign: 'notification/messages-campaign',
  customerSegment: 'notification/customer-segment',
  tableMigration: 'table-migration',
  tableMigrationList: 'table-migration-list',
  blockUnblockUsers: 'block_unblock_users',
  forceUpdate: 'force_update',
  blockListCountry: 'block_list_country',
  blockListCurrency: 'block_list_currency',
  blockListBeneficiary: 'block_list_beneficiary',
  blockListIban: 'block_list_iban',
  domainManagement: 'domain_management',
  productManagement: 'product_management',
  subProductManagement: 'sub_product_management',
  accessManagement: 'access_management',
  manageUser: 'manage_user',
  groupManagement: 'group_management',
  roleManagement: 'role-management',
  ruleManagement: 'rule-management',
  masterUnitConfig: 'master_unit_config',
  masterCurrencyConfig: 'master_currency_config',
  masterCountryConfig: 'master_country_config',
  masterLanguageConfig: 'master_language_config',
  masterChannelConfig: 'master_channel_config',
  comingSoonScreen: 'coming_soon_screen',
  partnerProfile: 'partner_profile',
  pendingRequest: 'pending-request',
  pendingApproval: 'pending-approval',
  partnerListing: 'partner_listing',
  loginUrl: 'auth-server/login',
  generateAccessToken: 'token/generate',
}

export default menuScreenUrls
