/** Route path constants — seeded from Flutter app_router.dart */
const routes = {
  login: '/login',
  root: '/',
  dashboard: '/dashboard',
  home: '/dashboard',
  city: '/dashboard/city',
  customer_journey: '/customer-journey',
  transaction_error_details: '/transaction-error-details',
  i18n_management: '/dashboard/i18n-management',
  banner_configuration: '/dashboard/banner-configuration',
  child_management: '/dashboard/child_management',
  menu_entitlement: '/dashboard/menu-entitlement',
  term_condition: '/dashboard/term-condition',
  notification_push_notification: '/dashboard/notification/push-notification',
  notification_messages_campaign: '/dashboard/notification/messages-campaign',
  notification_customer_segment: '/dashboard/notification/customer-segment',
  customer_segment: '/customer-segment',
  customer_segment_2: '/dashboard/customer-segment',
  table_migration: '/dashboard/table-migration',
  table_migration_list: '/dashboard/table-migration-list',
  role_management: '/dashboard/role-management',
  segment_access_management: '/dashboard/segment_access_management',
  rule_management: '/dashboard/rule-management',
  block_user: '/dashboard/block_user',
  force_update: '/dashboard/force_update',
  group_manage_add: '/dashboard/group_manage_add',
  group_manage_edit: '/dashboard/group_manage_edit',
  domain_management: '/dashboard/domain_management',
  product_management: '/dashboard/product_management',
  retail_product: '/dashboard/retail_product',
  transfer_limit: '/dashboard/transfer_limit',
  fees_limit: '/dashboard/fees_limit',
  apply_product: '/dashboard/apply_product',
  faq_management: '/dashboard/faq_management',
  subproduct: '/dashboard/subproduct',
  apply_product_subproduct: '/dashboard/apply_product_subproduct',
  link_configuration: '/dashboard/link_configuration',
  User_name: '/dashboard/User_name',
  access_product_management: '/dashboard/access_product_management',
  atm_locator: '/dashboard/atm_locator',
  crm_department: '/dashboard/crm_department',
  crm_service_management: '/dashboard/crm_service_management',
  branch_locator: '/dashboard/branch_locator',
  kiosk_locator: '/dashboard/kiosk_locator',
  master_category_management: '/dashboard/master_category_management',
  otp_config: '/dashboard/otp_config',
  offer_management: '/dashboard/offer_management',
  discount_management: '/dashboard/discount_management',
  user_creation: '/dashboard/user_creation',
  mfa_management: '/dashboard/mfa_management',
  sub_product_management: '/dashboard/sub_product_management',
  group_management: '/dashboard/group_management',
  beneficiary_nav: '/dashboard/beneficiary_nav',
  beneficiary_add: '/dashboard/beneficiary_add',
  beneficiary_edit: '/dashboard/beneficiary_edit',
  retail_subproduct: '/dashboard/retail_subproduct',
  error_management: '/dashboard/error_management',
  country_nav: '/dashboard/country_nav',
  unit_nav: '/dashboard/unit_nav',
  currency_nav: '/dashboard/currency_nav',
  master_currency_nav: '/dashboard/master_currency_nav',
  iban_nav: '/dashboard/iban_nav',
  master_country_nav: '/dashboard/master_country_nav',
  fingerprint_management: '/dashboard/fingerprint_management',
  logging_exception: '/dashboard/logging_exception',
  logging_event: '/dashboard/logging_event',
  bo_user_action: '/dashboard/bo_user_action',
  master_language_nav: '/dashboard/master_language_nav',
  channel_nav: '/dashboard/channel_nav',
  change_password: '/dashboard/change_password',
  coming_soon: '/dashboard/coming_soon',
  partner_stepper: '/dashboard/partner_stepper',
  pending_request_nav: '/dashboard/pending-request-nav',
  pending_approval_nav: '/dashboard/pending_approval_nav',
  Partner_Listing: '/dashboard/Partner_Listing',
  customer_search: '/dashboard/customer_search',
  utility_service_management: '/dashboard/utility_service_management',
  error_configuration: '/dashboard/error_configuration',
  template_creation: '/dashboard/template_creation',
  License_Management: '/dashboard/License_Management',
  Parameter_Maintenance: '/dashboard/Parameter_Maintenance',
  BlockList_IP: '/dashboard/BlockList_IP',
  configuration_para: '/dashboard/configuration_para',
  Notifications_Management: '/dashboard/Notifications_Management',
  Ready_To_Sync: '/dashboard/Ready_To_Sync',
  password_policy: '/dashboard/password_policy',
  password_configurations: '/dashboard/password_configurations',
  theme_config: '/dashboard/theme_config',
  database_config: '/dashboard/database_config',
  blocklist_imei: '/dashboard/blocklist_imei',
  bank_management: '/dashboard/bank_management',
  beneficiary_cooling_off: '/dashboard/beneficiary_cooling_off',
  beneficiary_cooling_pending: '/dashboard/beneficiary_cooling_pending',
  terms_condition_disclaimer: '/dashboard/terms&condition_disclaimer',
  account_class: '/dashboard/account_class',
  account_type: '/dashboard/account_type',
  lookup_types: '/dashboard/lookup_types',
  lookups: '/dashboard/lookups',
  transfer_control: '/dashboard/transfer_control',
  default_parameter: '/dashboard/default_parameter',
  application_version_management: '/dashboard/application_version_management',
  western_union_email: '/dashboard/western_union_email',
  western_union_history: '/dashboard/western_union_history',
  rtp_transfer_purpose_management: '/dashboard/rtp_transfer_purpose_management',
  connectivity_hub: '/dashboard/connectivity_hub',
  transaction_error_table: '/dashboard/transaction-error-table',
  transaction_error_details_landing: '/dashboard/transaction-error-details-landing',
  direct_remittance_type: '/dashboard/direct_remittance_type',
  rtp_account_type_management: '/dashboard/rtp_account_type_management',
  direct_remittance: '/dashboard/direct_remittance',
  cheque_book_management: '/dashboard/cheque_book_management',
  afaq_management: '/dashboard/afaq_management',
  cheque_deposit: '/dashboard/cheque_deposit',
  category_code: '/dashboard/category_code',
  preference: '/dashboard/preference',
  reach_us: '/dashboard/reach_us',
  profanity_check: '/dashboard/profanity_check',
  card: '/dashboard/card',
  charity_management: '/dashboard/charity_management',
  card_spend: '/dashboard/card_spend',
  google_pay: '/dashboard/google_pay',
  apple_pay: '/dashboard/apple_pay',
  android_config: '/dashboard/android_config',
  consolidate_e_statement: '/dashboard/consolidate_e_statement',
  card_issuance_management: '/dashboard/card_issuance_management',
  transfer_type: '/dashboard/transfer_type',
  fawran_rules: '/dashboard/fawran_rules',
  global_transfer_limit: '/dashboard/global_transfer_limit',
  mq_configuration: '/dashboard/mq_configuration',
  otp_bio_matrix: '/dashboard/otp-bio_matrix',
  role_based_access: '/dashboard/role_based_access',
  profile_control: '/dashboard/profile_control',
  instant_finance: '/dashboard/instant_finance',
  merchant_management: '/dashboard/merchant_management',
  salary_advance: '/dashboard/salary_advance',
  finance_offer: '/dashboard/finance_offer',
  finance_calculator: '/dashboard/finance_calculator',
  report_template_maintanance: '/dashboard/report_template_maintanance',
  ready_to_sync_table: '/dashboard/ready_to_sync_table',
  athkar_management: '/dashboard/athkar_management',
  oci_user_management: '/dashboard/oci_user_management',
  offer_static_info: '/dashboard/offer_static_info',
  offers_category: '/dashboard/offers_category',
  offers_rewards_management: '/dashboard/offers_rewards_management',
  oci_user_notification: '/dashboard/oci_user_notification',
  gateway_sync: '/dashboard/gateway_sync',
  release_management: '/dashboard/release_management',
  splash_screen_maintenance: '/dashboard/splash_screen_maintenance',
  data_cleansing: '/dashboard/data_cleansing',
  rm_contact: '/dashboard/rm_contact',
  error_master: '/dashboard/error_master',
  sms_configuration: '/dashboard/sms_configuration',
  stories_management: '/dashboard/stories_management',
  story_report: '/dashboard/story_report',
  onboarding_management: '/dashboard/onboarding_management',
  sector: '/dashboard/sector',
  sector_management: '/dashboard/sector_management',
  mccg: '/dashboard/mccg',
  favorite: '/dashboard/favorite',
  widget: '/dashboard/widget',
  favorite_list: '/dashboard/favorite_list',
  risk_mangement: '/dashboard/risk_mangement',
  dc_city_master: '/dashboard/dc_city_master',
  onboarding_product_configuration: '/dashboard/onboarding_product_configuration',
  employment_masters: '/dashboard/employment_masters',
  notification_template: '/dashboard/notification_template',
  adapter_table: '/dashboard/adapter_table',
  api_call: '/dashboard/api_call',
  dynamic_screen: '/dashboard/dynamic_screen',
  gateway_configuration: '/dashboard/gateway_configuration',
  eIPO_company_configuration: '/dashboard/eIPO_company_configuration',
  funnel: '/dashboard/funnel',
  product_content_management: '/dashboard/product_content_management',
  products_management: '/dashboard/products _management',
  about_Qnb: '/dashboard/about_Qnb',
  profile_control_2: '/profile_control',
  instant_finance_2: '/instant_finance',
  merchant_management_2: '/merchant_management',
  show_case: '/show-case',
  app_library: '/app-library',
  pending_request: '/pending-request',
  pending_approval: '/pending_approval',
}

/** All dashboard child paths for stub registration */
export const dashboardChildPaths = [
  'city',
  'customer-journey',
  'transaction-error-details',
  'i18n-management',
  'banner-configuration',
  'child_management',
  'menu-entitlement',
  'term-condition',
  'notification/push-notification',
  'notification/messages-campaign',
  'notification/customer-segment',
  'customer-segment',
  'table-migration',
  'table-migration-list',
  'role-management',
  'segment_access_management',
  'rule-management',
  'block_user',
  'force_update',
  'group_manage_add',
  'group_manage_edit',
  'domain_management',
  'product_management',
  'retail_product',
  'transfer_limit',
  'fees_limit',
  'apply_product',
  'faq_management',
  'subproduct',
  'apply_product_subproduct',
  'link_configuration',
  'User_name',
  'access_product_management',
  'atm_locator',
  'crm_department',
  'crm_service_management',
  'branch_locator',
  'kiosk_locator',
  'master_category_management',
  'otp_config',
  'offer_management',
  'discount_management',
  'user_creation',
  'mfa_management',
  'sub_product_management',
  'group_management',
  'beneficiary_nav',
  'beneficiary_add',
  'beneficiary_edit',
  'retail_subproduct',
  'error_management',
  'country_nav',
  'unit_nav',
  'currency_nav',
  'master_currency_nav',
  'iban_nav',
  'master_country_nav',
  'fingerprint_management',
  'logging_exception',
  'logging_event',
  'bo_user_action',
  'master_language_nav',
  'channel_nav',
  'change_password',
  'coming_soon',
  'partner_stepper',
  'pending-request-nav',
  'pending_approval_nav',
  'Partner_Listing',
  'customer_search',
  'utility_service_management',
  'error_configuration',
  'template_creation',
  'License_Management',
  'Parameter_Maintenance',
  'BlockList_IP',
  'configuration_para',
  'Notifications_Management',
  'Ready_To_Sync',
  'password_policy',
  'password_configurations',
  'theme_config',
  'database_config',
  'blocklist_imei',
  'bank_management',
  'beneficiary_cooling_off',
  'beneficiary_cooling_pending',
  'terms&condition_disclaimer',
  'account_class',
  'account_type',
  'lookup_types',
  'lookups',
  'transfer_control',
  'default_parameter',
  'application_version_management',
  'western_union_email',
  'western_union_history',
  'rtp_transfer_purpose_management',
  'connectivity_hub',
  'transaction-error-table',
  'transaction-error-details-landing',
  'direct_remittance_type',
  'rtp_account_type_management',
  'direct_remittance',
  'cheque_book_management',
  'afaq_management',
  'cheque_deposit',
  'category_code',
  'preference',
  'reach_us',
  'profanity_check',
  'card',
  'charity_management',
  'card_spend',
  'google_pay',
  'apple_pay',
  'android_config',
  'consolidate_e_statement',
  'card_issuance_management',
  'transfer_type',
  'fawran_rules',
  'global_transfer_limit',
  'mq_configuration',
  'otp-bio_matrix',
  'role_based_access',
  'profile_control',
  'instant_finance',
  'merchant_management',
  'salary_advance',
  'finance_offer',
  'finance_calculator',
  'report_template_maintanance',
  'ready_to_sync_table',
  'athkar_management',
  'oci_user_management',
  'offer_static_info',
  'offers_category',
  'offers_rewards_management',
  'oci_user_notification',
  'gateway_sync',
  'release_management',
  'splash_screen_maintenance',
  'data_cleansing',
  'rm_contact',
  'error_master',
  'sms_configuration',
  'stories_management',
  'story_report',
  'onboarding_management',
  'sector',
  'sector_management',
  'mccg',
  'favorite',
  'widget',
  'favorite_list',
  'risk_mangement',
  'dc_city_master',
  'onboarding_product_configuration',
  'employment_masters',
  'notification_template',
  'adapter_table',
  'api_call',
  'dynamic_screen',
  'gateway_configuration',
  'eIPO_company_configuration',
  'funnel',
  'product_content_management',
  'products _management',
  'about_Qnb',
  'show-case',
  'app-library',
  'pending-request',
  'pending_approval',
]

export default routes
